"""配置层：plan-driven 网络配置、v2.3 版本化架构配置与 M0 实验配置。

- `plans.Plan3DConfig`：只读解析冻结的 nnUNetPlans.json（3d_fullres）；
- `architecture.ArchitectureSpec`：v2.3 版本化架构配置 + 稳定 SHA-256 架构哈希 + §8.6 浅层 skip 契约 + 身份校验；
- `experiment.load_experiment_config`：加载实验配置（legacy `m0_picai_3d_fullres.yaml` 或 v2.3
  `m0_resenc_picai_3d_fullres_v23.yaml`）；
- `experiment.validate_against_plan`：检查配置与 plan / 项目约定冲突。
"""
from .architecture import (
    ACTIVATION_ORDER_POST,
    BLOCK_TYPE_BASIC,
    ENCODER_TYPE_PLAIN,
    ENCODER_TYPE_RESIDUAL,
    FUSION_STAGE,
    SHALLOW_SKIP_CONTRACT,
    SHALLOW_SKIP_CONTRACT_ID,
    ArchitectureConfigError,
    ArchitectureIdentityError,
    ArchitectureRef,
    ArchitectureSpec,
    architecture_sha256,
    architecture_spec_from_mapping,
    assert_shallow_skip_inputs_allowed,
    canonical_json,
    load_architecture_config,
    sha256_text,
    validate_architecture_against_plan,
    validate_shallow_skip_contract,
    verify_architecture_identity,
)
from .experiment import (
    DEFAULT_PENDING_PARITY,
    MODALITY_ORDER,
    PROJECT_ROOT,
    AugmentationConfig,
    EarlyStoppingConfigFile,
    ExperimentConfigError,
    InferenceConfig,
    M0ExperimentConfig,
    ValidationConfig,
    load_experiment_config,
    read_split_summary,
    validate_against_plan,
    validate_validation_protocol,
    validation_protocol_from_config,
)
from .plans import Plan3DConfig, PlanConfigError, load_plan

__all__ = [
    "ACTIVATION_ORDER_POST",
    "BLOCK_TYPE_BASIC",
    "DEFAULT_PENDING_PARITY",
    "ENCODER_TYPE_PLAIN",
    "ENCODER_TYPE_RESIDUAL",
    "FUSION_STAGE",
    "MODALITY_ORDER",
    "PROJECT_ROOT",
    "SHALLOW_SKIP_CONTRACT",
    "SHALLOW_SKIP_CONTRACT_ID",
    "ArchitectureConfigError",
    "ArchitectureIdentityError",
    "ArchitectureRef",
    "ArchitectureSpec",
    "AugmentationConfig",
    "EarlyStoppingConfigFile",
    "ExperimentConfigError",
    "InferenceConfig",
    "M0ExperimentConfig",
    "Plan3DConfig",
    "PlanConfigError",
    "ValidationConfig",
    "architecture_sha256",
    "architecture_spec_from_mapping",
    "assert_shallow_skip_inputs_allowed",
    "canonical_json",
    "load_architecture_config",
    "load_experiment_config",
    "load_plan",
    "read_split_summary",
    "sha256_text",
    "validate_against_plan",
    "validate_architecture_against_plan",
    "validate_shallow_skip_contract",
    "validate_validation_protocol",
    "validation_protocol_from_config",
    "verify_architecture_identity",
]
